// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoYwI3Nn-xC-faaeBKz6XeZIaUQfT7aM4',
    appId: '1:616828888404:android:cab5cf042fcfd0eb5454c1',
    messagingSenderId: '616828888404',
    projectId: 'omni-91c4e',
    storageBucket: 'omni-91c4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg5Y-Pc_zxlvz7GwbG7MvlYO94Es-kwb4',
    appId: '1:616828888404:ios:c81d79d8564b5a305454c1',
    messagingSenderId: '616828888404',
    projectId: 'omni-91c4e',
    storageBucket: 'omni-91c4e.firebasestorage.app',
    androidClientId: '616828888404-lrejvc9t6t1lbh5v60um8fhdls0d8uhc.apps.googleusercontent.com',
    iosClientId: '616828888404-rfv7fokliu4ifhsq3dkv54rtqelleek6.apps.googleusercontent.com',
    iosBundleId: 'com.rideapp.userApp',
  );
}
